apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: storage-backend-dev-deployment
  labels:
    app: storage-backend-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-backend-dev
  template:
    metadata:
      labels:
        app: storage-backend-dev
    spec:
      hostname: storage-backend-dev
      containers:
        - name: storage-backend-dev
          image: 408153089286.dkr.ecr.ap-south-1.amazonaws.com/storage-backend-dev:<VERSION>
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: '2048Mi'
              cpu: '1'
            limits:
              memory: '4096Mi'
              cpu: '2'
          readinessProbe:
              httpGet:
                path:  /health
                port: 3000
              initialDelaySeconds: 30
              timeoutSeconds: 10
          livenessProbe:
              httpGet:
                path:  /health
                port: 3000
              initialDelaySeconds: 30
              periodSeconds: 5
              timeoutSeconds: 10
              failureThreshold: 4
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  key: PORT
                  name: dev-storage-backend
            - name: HOST
              valueFrom:
                secretKeyRef:
                  key: HOST
                  name: dev-storage-backend
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: GOOGLE_CLIENT_ID
                  name: dev-storage-backend
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: GOOGLE_CLIENT_SECRET
                  name: dev-storage-backend
            - name: GOOGLE_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  key: GOOGLE_REDIRECT_URI
                  name: dev-storage-backend
            - name: MYIPR_BASE_URL
              valueFrom:
                secretKeyRef:
                  key: MYIPR_BASE_URL
                  name: dev-storage-backend
            - name: MYIPR_PROFILE_URL
              valueFrom:
                secretKeyRef:
                  key: MYIPR_PROFILE_URL
                  name: dev-storage-backend
            - name: DBX_APP_KEY
              valueFrom:
                secretKeyRef:
                  key: DBX_APP_KEY
                  name: dev-storage-backend
            - name: DBX_APP_SECRET
              valueFrom:
                secretKeyRef:
                  key: DBX_APP_SECRET
                  name: dev-storage-backend
            - name: DBX_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  key: DBX_REDIRECT_URI
                  name: dev-storage-backend
            - name: ONEDRIVE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: ONEDRIVE_CLIENT_ID
                  name: dev-storage-backend
            - name: ONEDRIVE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: ONEDRIVE_CLIENT_SECRET
                  name: dev-storage-backend
            - name: ONEDRIVE_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  key: ONEDRIVE_REDIRECT_URI
                  name: dev-storage-backend
            - name: ONEDRIVE_SCOPE
              valueFrom:
                secretKeyRef:
                  key: ONEDRIVE_SCOPE
                  name: dev-storage-backend
            - name: ONEDRIVE_GRANT_TYPE
              valueFrom:
                secretKeyRef:
                  key: ONEDRIVE_GRANT_TYPE
                  name: dev-storage-backend
            - name: AWS_PUBLIC_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  key: AWS_PUBLIC_BUCKET_NAME
                  name: dev-storage-backend 
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  key: AWS_REGION
                  name: dev-storage-backend      
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: AWS_ACCESS_KEY_ID
                  name: dev-storage-backend
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: AWS_SECRET_ACCESS_KEY
                  name: dev-storage-backend      
---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: storage-backend-dev-svc
  labels:
    svc: storage-backend-dev
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: storage-backend-dev
