apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: qa
  name: mai-experience-frontend-qa-deployment
  labels:
    app: mai-experience-frontend-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mai-experience-frontend-qa
  template:
    metadata:
      labels:
        app: mai-experience-frontend-qa
    spec:
      hostname: mai-experience-frontend-qa
      containers:
        - name: mai-experience-frontend-qa
          image: 408153089286.dkr.ecr.ap-south-1.amazonaws.com/mai-experience-frontend-qa:<VERSION>
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: '1024Mi'
              cpu: '500m'
            limits:
              memory: '2048Mi'
              cpu: '750m'
          # readinessProbe:
          #     httpGet:
          #       path: /health
          #       port: 5174
          #     initialDelaySeconds: 30
          #     timeoutSeconds: 10
          # livenessProbe:
          #     httpGet:
          #       path: /health
          #       port: 5174
          #     initialDelaySeconds: 30
          #     periodSeconds: 5
          #     timeoutSeconds: 10
          #     failureThreshold: 4
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # env:
          #   - name: PORT
          #     valueFrom:
          #       secretKeyRef:
          #         key: PORT
          #         name: qa-mai-experience-frontend
---
apiVersion: v1
kind: Service
metadata:
  namespace: qa
  name: mai-experience-frontend-qa-svc
  labels:
    svc: mai-experience-frontend-qa
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: mai-experience-frontend-qa